# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0
    - name: restore nuget pkg
      run: nuget restore Launcher-Cli.sln
    - name: build solution
      run: msbuild.exe Launcher-Cli.sln /property:Configuration=Release
    - name: Push Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
          name: Launcher
          path: 
            /Release/Launcher-Cli.exe
            /Release/Newtonsoft.Json.dll
